/**
 * European Events Calendar for Event Builder
 * Includes national holidays, religious holidays, and major cultural festivals
 * These represent prime opportunities for GAA tournaments
 */

export interface EuropeanEvent {
  date: string; // ISO date YYYY-MM-DD (for fixed dates) or "variable" for moving dates
  name: string;
  country: string;
  countryCode: string;
  type: "national" | "religious" | "festival" | "cultural";
  description: string;
  travelAppeal: "high" | "medium" | "low"; // How attractive for GAA travel
  typicalDuration: number; // Days
  wikiUrl?: string; // Wikipedia link for more info
}

// 2025 European Events Calendar
export const europeanEvents2025: EuropeanEvent[] = [
  // SPAIN
  {
    date: "2025-01-06",
    name: "Three Kings Day (Epiphany)",
    country: "Spain",
    countryCode: "ES",
    type: "religious",
    description:
      "Major gift-giving holiday in Spain, big parades and celebrations",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2025-02-28",
    name: "Andalusia Day",
    country: "Spain",
    countryCode: "ES",
    type: "national",
    description:
      "Regional holiday in Andalusia - great for southern Spain events",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2025-03-15",
    name: "Las Fallas (Valencia)",
    country: "Spain",
    countryCode: "ES",
    type: "festival",
    description:
      "Massive fire festival in Valencia with parades, fireworks, and celebrations",
    travelAppeal: "high",
    typicalDuration: 5,
    wikiUrl: "https://en.wikipedia.org/wiki/Falles",
  },
  {
    date: "2025-04-13",
    name: "Semana Santa (Holy Week)",
    country: "Spain",
    countryCode: "ES",
    type: "religious",
    description: "Major religious festival across Spain with processions",
    travelAppeal: "high",
    typicalDuration: 7,
    wikiUrl: "https://en.wikipedia.org/wiki/Holy_Week_in_Spain",
  },
  {
    date: "2025-04-14",
    name: "Feria de Abril (Seville)",
    country: "Spain",
    countryCode: "ES",
    type: "festival",
    description:
      "Famous spring fair in Seville - flamenco, horses, celebrations",
    travelAppeal: "high",
    typicalDuration: 6,
    wikiUrl: "https://en.wikipedia.org/wiki/Seville_Fair",
  },
  {
    date: "2025-05-01",
    name: "Labour Day",
    country: "Spain",
    countryCode: "ES",
    type: "national",
    description: "Public holiday across Spain",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-06-24",
    name: "San Juan (Midsummer)",
    country: "Spain",
    countryCode: "ES",
    type: "festival",
    description:
      "Beach bonfires and celebrations, especially in coastal cities",
    travelAppeal: "high",
    typicalDuration: 1,
    wikiUrl: "https://en.wikipedia.org/wiki/St_John%27s_Eve#Spain",
  },
  {
    date: "2025-07-06",
    name: "San Fermín (Pamplona)",
    country: "Spain",
    countryCode: "ES",
    type: "festival",
    description: "Famous Running of the Bulls festival",
    travelAppeal: "high",
    typicalDuration: 9,
    wikiUrl: "https://en.wikipedia.org/wiki/San_Ferm%C3%ADn",
  },
  {
    date: "2025-08-15",
    name: "Assumption Day",
    country: "Spain",
    countryCode: "ES",
    type: "religious",
    description: "Major religious holiday, many local fiestas",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2025-08-28",
    name: "La Tomatina (Buñol)",
    country: "Spain",
    countryCode: "ES",
    type: "festival",
    description: "World-famous tomato fight festival near Valencia",
    travelAppeal: "high",
    typicalDuration: 1,
    wikiUrl: "https://en.wikipedia.org/wiki/La_Tomatina",
  },
  {
    date: "2025-10-12",
    name: "National Day of Spain",
    country: "Spain",
    countryCode: "ES",
    type: "national",
    description: "Spanish National Day - public holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-12-06",
    name: "Constitution Day",
    country: "Spain",
    countryCode: "ES",
    type: "national",
    description:
      "Public holiday, often creates long weekend with Immaculate Conception",
    travelAppeal: "medium",
    typicalDuration: 1,
  },

  // PORTUGAL
  {
    date: "2025-02-25",
    name: "Carnival",
    country: "Portugal",
    countryCode: "PT",
    type: "festival",
    description:
      "Major carnival celebrations, especially in Lisbon and Madeira",
    travelAppeal: "high",
    typicalDuration: 4,
    wikiUrl: "https://en.wikipedia.org/wiki/Carnival_in_Portugal",
  },
  {
    date: "2025-04-25",
    name: "Freedom Day",
    country: "Portugal",
    countryCode: "PT",
    type: "national",
    description: "Celebrates the Carnation Revolution - major national holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-05-01",
    name: "Labour Day",
    country: "Portugal",
    countryCode: "PT",
    type: "national",
    description: "Public holiday across Portugal",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-06-10",
    name: "Portugal Day",
    country: "Portugal",
    countryCode: "PT",
    type: "national",
    description: "National Day of Portugal - major celebrations",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-06-13",
    name: "Santo António (Lisbon)",
    country: "Portugal",
    countryCode: "PT",
    type: "festival",
    description: "Lisbon's biggest festival - street parties, sardines, music",
    travelAppeal: "high",
    typicalDuration: 3,
    wikiUrl: "https://en.wikipedia.org/wiki/Festas_de_Lisboa",
  },
  {
    date: "2025-06-24",
    name: "São João (Porto)",
    country: "Portugal",
    countryCode: "PT",
    type: "festival",
    description: "Porto's famous midsummer festival with street parties",
    travelAppeal: "high",
    typicalDuration: 2,
    wikiUrl:
      "https://en.wikipedia.org/wiki/Festa_de_S%C3%A3o_Jo%C3%A3o_do_Porto",
  },
  {
    date: "2025-08-15",
    name: "Assumption Day",
    country: "Portugal",
    countryCode: "PT",
    type: "religious",
    description: "Public holiday with local festivals",
    travelAppeal: "medium",
    typicalDuration: 1,
  },

  // GERMANY
  {
    date: "2025-02-27",
    name: "Carnival (Karneval/Fasching)",
    country: "Germany",
    countryCode: "DE",
    type: "festival",
    description:
      "Major carnival celebrations, especially in Cologne and Düsseldorf",
    travelAppeal: "high",
    typicalDuration: 6,
    wikiUrl: "https://en.wikipedia.org/wiki/Carnival_in_Germany",
  },
  {
    date: "2025-05-01",
    name: "Labour Day",
    country: "Germany",
    countryCode: "DE",
    type: "national",
    description: "Public holiday across Germany",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-06-19",
    name: "Corpus Christi",
    country: "Germany",
    countryCode: "DE",
    type: "religious",
    description: "Public holiday in several German states",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2025-09-20",
    name: "Oktoberfest (Munich)",
    country: "Germany",
    countryCode: "DE",
    type: "festival",
    description: "World's largest beer festival - 6 million visitors annually",
    travelAppeal: "high",
    typicalDuration: 16,
    wikiUrl: "https://en.wikipedia.org/wiki/Oktoberfest",
  },
  {
    date: "2025-10-03",
    name: "German Unity Day",
    country: "Germany",
    countryCode: "DE",
    type: "national",
    description: "German National Day - public holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-12-06",
    name: "Christmas Markets Open",
    country: "Germany",
    countryCode: "DE",
    type: "cultural",
    description: "Famous Christmas markets across Germany begin",
    travelAppeal: "high",
    typicalDuration: 30,
    wikiUrl: "https://en.wikipedia.org/wiki/Christmas_market",
  },

  // NETHERLANDS
  {
    date: "2025-02-25",
    name: "Carnival",
    country: "Netherlands",
    countryCode: "NL",
    type: "festival",
    description:
      "Major carnival in southern Netherlands (Maastricht, Den Bosch)",
    travelAppeal: "high",
    typicalDuration: 3,
    wikiUrl: "https://en.wikipedia.org/wiki/Carnival_in_the_Netherlands",
  },
  {
    date: "2025-04-27",
    name: "King's Day",
    country: "Netherlands",
    countryCode: "NL",
    type: "national",
    description:
      "Biggest party in Netherlands - orange everywhere, street markets",
    travelAppeal: "high",
    typicalDuration: 1,
    wikiUrl: "https://en.wikipedia.org/wiki/Koningsdag",
  },
  {
    date: "2025-05-05",
    name: "Liberation Day",
    country: "Netherlands",
    countryCode: "NL",
    type: "national",
    description: "End of WWII occupation - festivals and concerts",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // FRANCE
  {
    date: "2025-02-25",
    name: "Nice Carnival",
    country: "France",
    countryCode: "FR",
    type: "festival",
    description: "One of the world's biggest carnivals on the Côte d'Azur",
    travelAppeal: "high",
    typicalDuration: 14,
    wikiUrl: "https://en.wikipedia.org/wiki/Nice_Carnival",
  },
  {
    date: "2025-05-01",
    name: "Labour Day",
    country: "France",
    countryCode: "FR",
    type: "national",
    description: "Public holiday across France",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-05-08",
    name: "Victory in Europe Day",
    country: "France",
    countryCode: "FR",
    type: "national",
    description: "WWII Victory Day - public holiday",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2025-06-21",
    name: "Fête de la Musique",
    country: "France",
    countryCode: "FR",
    type: "cultural",
    description: "Nationwide music festival - free concerts everywhere",
    travelAppeal: "high",
    typicalDuration: 1,
    wikiUrl: "https://en.wikipedia.org/wiki/F%C3%AAte_de_la_Musique",
  },
  {
    date: "2025-07-14",
    name: "Bastille Day",
    country: "France",
    countryCode: "FR",
    type: "national",
    description: "French National Day - fireworks, parades, celebrations",
    travelAppeal: "high",
    typicalDuration: 1,
    wikiUrl: "https://en.wikipedia.org/wiki/Bastille_Day",
  },

  // BELGIUM
  {
    date: "2025-02-25",
    name: "Carnival of Binche",
    country: "Belgium",
    countryCode: "BE",
    type: "festival",
    description: "UNESCO-listed carnival with famous Gilles characters",
    travelAppeal: "high",
    typicalDuration: 3,
    wikiUrl: "https://en.wikipedia.org/wiki/Carnival_of_Binche",
  },
  {
    date: "2025-07-21",
    name: "Belgian National Day",
    country: "Belgium",
    countryCode: "BE",
    type: "national",
    description: "National holiday with parades and celebrations",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-08-15",
    name: "Assumption Day",
    country: "Belgium",
    countryCode: "BE",
    type: "religious",
    description: "Public holiday with local festivals",
    travelAppeal: "medium",
    typicalDuration: 1,
  },

  // ITALY
  {
    date: "2025-02-08",
    name: "Venice Carnival",
    country: "Italy",
    countryCode: "IT",
    type: "festival",
    description: "World-famous masked carnival in Venice",
    travelAppeal: "high",
    typicalDuration: 18,
    wikiUrl: "https://en.wikipedia.org/wiki/Carnival_of_Venice",
  },
  {
    date: "2025-04-25",
    name: "Liberation Day",
    country: "Italy",
    countryCode: "IT",
    type: "national",
    description: "End of WWII occupation - national holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-05-01",
    name: "Labour Day",
    country: "Italy",
    countryCode: "IT",
    type: "national",
    description: "Public holiday across Italy",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-06-02",
    name: "Republic Day",
    country: "Italy",
    countryCode: "IT",
    type: "national",
    description: "Italian National Day with military parades",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-07-02",
    name: "Palio di Siena",
    country: "Italy",
    countryCode: "IT",
    type: "festival",
    description: "Famous historic horse race in Siena's main square",
    travelAppeal: "high",
    typicalDuration: 4,
  },
  {
    date: "2025-08-15",
    name: "Ferragosto",
    country: "Italy",
    countryCode: "IT",
    type: "national",
    description: "Major summer holiday - Italians head to beaches",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // AUSTRIA
  {
    date: "2025-05-01",
    name: "Labour Day",
    country: "Austria",
    countryCode: "AT",
    type: "national",
    description: "Public holiday across Austria",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-10-26",
    name: "Austrian National Day",
    country: "Austria",
    countryCode: "AT",
    type: "national",
    description: "National holiday with celebrations",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2025-12-05",
    name: "Krampusnacht",
    country: "Austria",
    countryCode: "AT",
    type: "cultural",
    description: "Traditional Krampus parades across Austria",
    travelAppeal: "medium",
    typicalDuration: 1,
  },

  // CZECH REPUBLIC
  {
    date: "2025-05-08",
    name: "Victory Day",
    country: "Czech Republic",
    countryCode: "CZ",
    type: "national",
    description: "End of WWII - national holiday",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2025-09-28",
    name: "Czech Statehood Day",
    country: "Czech Republic",
    countryCode: "CZ",
    type: "national",
    description: "National holiday celebrating Czech statehood",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // SWITZERLAND
  {
    date: "2025-08-01",
    name: "Swiss National Day",
    country: "Switzerland",
    countryCode: "CH",
    type: "national",
    description: "Swiss National Day with fireworks and celebrations",
    travelAppeal: "high",
    typicalDuration: 1,
  },
];

// 2026 European Events Calendar
export const europeanEvents2026: EuropeanEvent[] = [
  // SPAIN
  {
    date: "2026-01-06",
    name: "Three Kings Day (Epiphany)",
    country: "Spain",
    countryCode: "ES",
    type: "religious",
    description: "Major gift-giving holiday in Spain",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-03-15",
    name: "Las Fallas (Valencia)",
    country: "Spain",
    countryCode: "ES",
    type: "festival",
    description: "Massive fire festival in Valencia",
    travelAppeal: "high",
    typicalDuration: 5,
    wikiUrl: "https://en.wikipedia.org/wiki/Falles",
  },
  {
    date: "2026-03-29",
    name: "Semana Santa (Holy Week)",
    country: "Spain",
    countryCode: "ES",
    type: "religious",
    description: "Major religious festival across Spain",
    travelAppeal: "high",
    typicalDuration: 7,
  },
  {
    date: "2026-05-01",
    name: "Labour Day",
    country: "Spain",
    countryCode: "ES",
    type: "national",
    description: "Public holiday across Spain",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-05-01",
    name: "Labour Day",
    country: "France",
    countryCode: "FR",
    type: "national",
    description: "Public holiday across France",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-05-01",
    name: "Labour Day",
    country: "Germany",
    countryCode: "DE",
    type: "national",
    description: "Public holiday across Germany",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-05-01",
    name: "Labour Day",
    country: "Portugal",
    countryCode: "PT",
    type: "national",
    description: "Public holiday across Portugal",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-05-01",
    name: "Labour Day",
    country: "Italy",
    countryCode: "IT",
    type: "national",
    description: "Public holiday across Italy",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-05-01",
    name: "Labour Day",
    country: "Belgium",
    countryCode: "BE",
    type: "national",
    description: "Public holiday across Belgium",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-06-24",
    name: "San Juan (Midsummer)",
    country: "Spain",
    countryCode: "ES",
    type: "festival",
    description: "Beach bonfires and celebrations",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-07-06",
    name: "San Fermín (Pamplona)",
    country: "Spain",
    countryCode: "ES",
    type: "festival",
    description: "Running of the Bulls festival",
    travelAppeal: "high",
    typicalDuration: 9,
    wikiUrl: "https://en.wikipedia.org/wiki/San_Ferm%C3%ADn",
  },
  {
    date: "2026-10-12",
    name: "National Day of Spain",
    country: "Spain",
    countryCode: "ES",
    type: "national",
    description: "Spanish National Day",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // PORTUGAL
  {
    date: "2026-02-17",
    name: "Carnival",
    country: "Portugal",
    countryCode: "PT",
    type: "festival",
    description: "Major carnival celebrations",
    travelAppeal: "high",
    typicalDuration: 4,
  },
  {
    date: "2026-04-25",
    name: "Freedom Day",
    country: "Portugal",
    countryCode: "PT",
    type: "national",
    description: "Major national holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-06-10",
    name: "Portugal Day",
    country: "Portugal",
    countryCode: "PT",
    type: "national",
    description: "National Day of Portugal",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-06-13",
    name: "Santo António (Lisbon)",
    country: "Portugal",
    countryCode: "PT",
    type: "festival",
    description: "Lisbon's biggest festival",
    travelAppeal: "high",
    typicalDuration: 3,
  },
  {
    date: "2026-06-24",
    name: "São João (Porto)",
    country: "Portugal",
    countryCode: "PT",
    type: "festival",
    description: "Porto's famous midsummer festival",
    travelAppeal: "high",
    typicalDuration: 2,
  },

  // GERMANY
  {
    date: "2026-02-17",
    name: "Carnival (Karneval/Fasching)",
    country: "Germany",
    countryCode: "DE",
    type: "festival",
    description: "Major carnival celebrations",
    travelAppeal: "high",
    typicalDuration: 6,
  },
  {
    date: "2026-09-19",
    name: "Oktoberfest (Munich)",
    country: "Germany",
    countryCode: "DE",
    type: "festival",
    description: "World's largest beer festival",
    travelAppeal: "high",
    typicalDuration: 16,
    wikiUrl: "https://en.wikipedia.org/wiki/Oktoberfest",
  },
  {
    date: "2026-10-03",
    name: "German Unity Day",
    country: "Germany",
    countryCode: "DE",
    type: "national",
    description: "German National Day",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // NETHERLANDS
  {
    date: "2026-04-27",
    name: "King's Day",
    country: "Netherlands",
    countryCode: "NL",
    type: "national",
    description: "Biggest party in Netherlands",
    travelAppeal: "high",
    typicalDuration: 1,
    wikiUrl: "https://en.wikipedia.org/wiki/Koningsdag",
  },
  {
    date: "2026-05-05",
    name: "Liberation Day",
    country: "Netherlands",
    countryCode: "NL",
    type: "national",
    description: "National celebration",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // FRANCE
  {
    date: "2026-02-14",
    name: "Nice Carnival",
    country: "France",
    countryCode: "FR",
    type: "festival",
    description: "Major carnival on the Côte d'Azur",
    travelAppeal: "high",
    typicalDuration: 14,
  },
  {
    date: "2026-07-14",
    name: "Bastille Day",
    country: "France",
    countryCode: "FR",
    type: "national",
    description: "French National Day",
    travelAppeal: "high",
    typicalDuration: 1,
    wikiUrl: "https://en.wikipedia.org/wiki/Bastille_Day",
  },

  // ITALY
  {
    date: "2026-02-07",
    name: "Venice Carnival",
    country: "Italy",
    countryCode: "IT",
    type: "festival",
    description: "World-famous masked carnival",
    travelAppeal: "high",
    typicalDuration: 18,
    wikiUrl: "https://en.wikipedia.org/wiki/Carnival_of_Venice",
  },
  {
    date: "2026-04-25",
    name: "Liberation Day",
    country: "Italy",
    countryCode: "IT",
    type: "national",
    description: "National holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-06-02",
    name: "Republic Day",
    country: "Italy",
    countryCode: "IT",
    type: "national",
    description: "Italian National Day",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-08-15",
    name: "Ferragosto",
    country: "Italy",
    countryCode: "IT",
    type: "national",
    description: "Major summer holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // BELGIUM
  {
    date: "2026-07-21",
    name: "Belgian National Day",
    country: "Belgium",
    countryCode: "BE",
    type: "national",
    description: "National holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // AUSTRIA
  {
    date: "2026-10-26",
    name: "Austrian National Day",
    country: "Austria",
    countryCode: "AT",
    type: "national",
    description: "National holiday",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // SWITZERLAND
  {
    date: "2026-08-01",
    name: "Swiss National Day",
    country: "Switzerland",
    countryCode: "CH",
    type: "national",
    description: "Swiss National Day",
    travelAppeal: "high",
    typicalDuration: 1,
  },

  // NOVEMBER 2026
  {
    date: "2026-11-01",
    name: "All Saints' Day",
    country: "Spain",
    countryCode: "ES",
    type: "religious",
    description: "Public holiday across Spain - families visit cemeteries",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-11-01",
    name: "All Saints' Day",
    country: "France",
    countryCode: "FR",
    type: "religious",
    description: "Public holiday in France",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-11-01",
    name: "All Saints' Day",
    country: "Italy",
    countryCode: "IT",
    type: "religious",
    description: "Public holiday in Italy",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-11-01",
    name: "All Saints' Day",
    country: "Belgium",
    countryCode: "BE",
    type: "religious",
    description: "Public holiday in Belgium",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-11-01",
    name: "All Saints' Day",
    country: "Portugal",
    countryCode: "PT",
    type: "religious",
    description: "Public holiday in Portugal",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-11-11",
    name: "Armistice Day",
    country: "France",
    countryCode: "FR",
    type: "national",
    description: "WWI remembrance - public holiday",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-11-11",
    name: "Armistice Day",
    country: "Belgium",
    countryCode: "BE",
    type: "national",
    description: "WWI remembrance - public holiday",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-11-15",
    name: "Repentance Day",
    country: "Germany",
    countryCode: "DE",
    type: "religious",
    description: "Regional holiday in some German states",
    travelAppeal: "low",
    typicalDuration: 1,
  },

  // DECEMBER 2026
  {
    date: "2026-12-01",
    name: "Restoration of Independence Day",
    country: "Portugal",
    countryCode: "PT",
    type: "national",
    description: "National holiday celebrating independence from Spain",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-12-05",
    name: "Christmas Markets Open",
    country: "Germany",
    countryCode: "DE",
    type: "cultural",
    description: "Famous Christmas markets across Germany",
    travelAppeal: "high",
    typicalDuration: 30,
    wikiUrl: "https://en.wikipedia.org/wiki/Christmas_market",
  },
  {
    date: "2026-12-06",
    name: "Constitution Day",
    country: "Spain",
    countryCode: "ES",
    type: "national",
    description: "Spanish Constitution Day - often creates long weekend",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-12-08",
    name: "Immaculate Conception",
    country: "Spain",
    countryCode: "ES",
    type: "religious",
    description: "Public holiday - combined with Constitution Day for puente",
    travelAppeal: "high",
    typicalDuration: 1,
  },
  {
    date: "2026-12-08",
    name: "Immaculate Conception",
    country: "Italy",
    countryCode: "IT",
    type: "religious",
    description: "Public holiday across Italy",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-12-08",
    name: "Immaculate Conception",
    country: "Portugal",
    countryCode: "PT",
    type: "religious",
    description: "Public holiday in Portugal",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-12-08",
    name: "Immaculate Conception",
    country: "Austria",
    countryCode: "AT",
    type: "religious",
    description: "Public holiday in Austria",
    travelAppeal: "medium",
    typicalDuration: 1,
  },
  {
    date: "2026-12-25",
    name: "Christmas Day",
    country: "Germany",
    countryCode: "DE",
    type: "religious",
    description: "Major holiday across Europe",
    travelAppeal: "low",
    typicalDuration: 2,
  },
  {
    date: "2026-12-26",
    name: "St. Stephen's Day",
    country: "Germany",
    countryCode: "DE",
    type: "religious",
    description: "Second Christmas Day - public holiday",
    travelAppeal: "low",
    typicalDuration: 1,
  },
  {
    date: "2026-12-26",
    name: "St. Stephen's Day",
    country: "Italy",
    countryCode: "IT",
    type: "religious",
    description: "Santo Stefano - public holiday",
    travelAppeal: "low",
    typicalDuration: 1,
  },
];

// Combined events
export const allEuropeanEvents: EuropeanEvent[] = [
  ...europeanEvents2025,
  ...europeanEvents2026,
];

// Get events by country
export function getEventsByCountry(countryCode: string): EuropeanEvent[] {
  return allEuropeanEvents.filter((e) => e.countryCode === countryCode);
}

// Get events in date range
export function getEventsInRange(
  startDate: Date,
  endDate: Date
): EuropeanEvent[] {
  return allEuropeanEvents.filter((e) => {
    const eventDate = new Date(e.date);
    return eventDate >= startDate && eventDate <= endDate;
  });
}

// Get high appeal events only
export function getHighAppealEvents(): EuropeanEvent[] {
  return allEuropeanEvents.filter((e) => e.travelAppeal === "high");
}

// Country flags
export const europeanCountryFlags: Record<string, string> = {
  ES: "🇪🇸",
  PT: "🇵🇹",
  DE: "🇩🇪",
  NL: "🇳🇱",
  FR: "🇫🇷",
  BE: "🇧🇪",
  IT: "🇮🇹",
  AT: "🇦🇹",
  CZ: "🇨🇿",
  CH: "🇨🇭",
  IE: "🇮🇪",
  GB: "🇬🇧",
};

// Event type colors
export const eventTypeColors: Record<string, string> = {
  national: "bg-blue-100 text-blue-800",
  religious: "bg-purple-100 text-purple-800",
  festival: "bg-orange-100 text-orange-800",
  cultural: "bg-green-100 text-green-800",
};
