import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Data extracted from GAA Demographics Report "No One Shouted Stop—Until Now"
// Published December 2025 by the GAA National Demographics Committee
// Source: Pages 34-49 (County Demographic Snapshots)

const provincesData = [
  { name: "Ulster", displayOrder: 1 },
  { name: "Munster", displayOrder: 2 },
  { name: "Leinster", displayOrder: 3 },
  { name: "Connacht", displayOrder: 4 },
];

// County data extracted from the report (pages 34-49)
const countiesData = [
  // ULSTER (9 counties)
  {
    name: "Antrim",
    province: "Ulster",
    displayOrder: 1,
    clubsGAA: 51,
    clubsLGFA: 36,
    clubsCamogie: 31,
    youthMalePlayers: 5589,
    youthFemalePlayers: 4798,
    fullMalePlayers: 2818,
    fullFemalePlayers: 1647,
    nonPlayers: 5036,
    totalPitches: 117,
    totalFloodlitPitches: 12,
    totalFullSizePitches: 72,
    teamsPerPitch: 6.3,
    teamsCamogie: 106,
    teamsLadiesFootball: 107,
    teamsHurling: 105,
    teamsFootball: 138,
    totalTeams: 456,
    populationFemale: 322096,
    populationMale: 319174,
    populationTotal: 651270,
    averageAge: 39.3,
    population0to5: 45363,
    population6to11: 50210,
  },
  {
    name: "Armagh",
    province: "Ulster",
    displayOrder: 2,
    clubsGAA: 49,
    clubsLGFA: 40,
    clubsCamogie: 17,
    youthMalePlayers: 5752,
    youthFemalePlayers: 4721,
    fullMalePlayers: 2367,
    fullFemalePlayers: 1413,
    nonPlayers: 8246,
    totalPitches: 120,
    totalFloodlitPitches: 31,
    totalFullSizePitches: 74,
    teamsPerPitch: 5.1,
    teamsCamogie: 22,
    teamsLadiesFootball: 128,
    teamsHurling: 23,
    teamsFootball: 210,
    totalTeams: 383,
    populationFemale: 98013,
    populationMale: 96385,
    populationTotal: 194398,
    averageAge: 37.92,
    population0to5: 15995,
    population6to11: 17404,
  },
  {
    name: "Cavan",
    province: "Ulster",
    displayOrder: 3,
    clubsGAA: 42,
    clubsLGFA: 34,
    clubsCamogie: 10,
    youthMalePlayers: 4244,
    youthFemalePlayers: 3881,
    fullMalePlayers: 1853,
    fullFemalePlayers: 1382,
    nonPlayers: 6240,
    totalPitches: 116,
    totalFloodlitPitches: 31,
    totalFullSizePitches: 71,
    teamsPerPitch: 2.8,
    teamsCamogie: 20,
    teamsLadiesFootball: 67,
    teamsHurling: 5,
    teamsFootball: 110,
    totalTeams: 202,
    populationFemale: 40644,
    populationMale: 41060,
    populationTotal: 81704,
    averageAge: 38.03,
    population0to5: 6346,
    population6to11: 7484,
  },
  {
    name: "Derry",
    province: "Ulster",
    displayOrder: 4,
    clubsGAA: 42,
    clubsLGFA: 30,
    clubsCamogie: 22,
    youthMalePlayers: 5637,
    youthFemalePlayers: 4478,
    fullMalePlayers: 2595,
    fullFemalePlayers: 1195,
    nonPlayers: 7511,
    totalPitches: 139,
    totalFloodlitPitches: 34,
    totalFullSizePitches: 74,
    teamsPerPitch: 5.6,
    teamsCamogie: 91,
    teamsLadiesFootball: 94,
    teamsHurling: 45,
    teamsFootball: 189,
    totalTeams: 418,
    populationFemale: 128413,
    populationMale: 124030,
    populationTotal: 252443,
    averageAge: 39.2,
    population0to5: 18760,
    population6to11: 20847,
  },
  {
    name: "Donegal",
    province: "Ulster",
    displayOrder: 5,
    clubsGAA: 40,
    clubsLGFA: 38,
    clubsCamogie: 7,
    youthMalePlayers: 6140,
    youthFemalePlayers: 4913,
    fullMalePlayers: 2688,
    fullFemalePlayers: 1149,
    nonPlayers: 8635,
    totalPitches: 107,
    totalFloodlitPitches: 12,
    totalFullSizePitches: 61,
    teamsPerPitch: 6.5,
    teamsCamogie: 13,
    teamsLadiesFootball: 151,
    teamsHurling: 25,
    teamsFootball: 208,
    totalTeams: 397,
    populationFemale: 84289,
    populationMale: 82795,
    populationTotal: 167084,
    averageAge: 39.6,
    population0to5: 11986,
    population6to11: 14240,
  },
  {
    name: "Down",
    province: "Ulster",
    displayOrder: 6,
    clubsGAA: 48,
    clubsLGFA: 43,
    clubsCamogie: 23,
    youthMalePlayers: 6834,
    youthFemalePlayers: 5330,
    fullMalePlayers: 2629,
    fullFemalePlayers: 1888,
    nonPlayers: 7625,
    totalPitches: 144,
    totalFloodlitPitches: 33,
    totalFullSizePitches: 89,
    teamsPerPitch: 6.6,
    teamsCamogie: 77,
    teamsLadiesFootball: 200,
    teamsHurling: 62,
    teamsFootball: 256,
    totalTeams: 595,
    populationFemale: 282504,
    populationMale: 270844,
    populationTotal: 553348,
    averageAge: 40.9,
    population0to5: 38038,
    population6to11: 42076,
  },
  {
    name: "Fermanagh",
    province: "Ulster",
    displayOrder: 7,
    clubsGAA: 23,
    clubsLGFA: 20,
    clubsCamogie: 0,
    youthMalePlayers: 2099,
    youthFemalePlayers: 1627,
    fullMalePlayers: 954,
    fullFemalePlayers: 434,
    nonPlayers: 2663,
    totalPitches: 53,
    totalFloodlitPitches: 13,
    totalFullSizePitches: 32,
    teamsPerPitch: 7.3,
    teamsCamogie: 0,
    teamsLadiesFootball: 104,
    teamsHurling: 17,
    teamsFootball: 110,
    totalTeams: 235,
    populationFemale: 31831,
    populationMale: 31768,
    populationTotal: 63599,
    averageAge: 40.7,
    population0to5: 4695,
    population6to11: 5144,
  },
  {
    name: "Monaghan",
    province: "Ulster",
    displayOrder: 8,
    clubsGAA: 32,
    clubsLGFA: 24,
    clubsCamogie: 4,
    youthMalePlayers: 3747,
    youthFemalePlayers: 3175,
    fullMalePlayers: 1528,
    fullFemalePlayers: 895,
    nonPlayers: 4707,
    totalPitches: 90,
    totalFloodlitPitches: 27,
    totalFullSizePitches: 57,
    teamsPerPitch: 5.8,
    teamsCamogie: 12,
    teamsLadiesFootball: 128,
    teamsHurling: 21,
    teamsFootball: 171,
    totalTeams: 331,
    populationFemale: 32394,
    populationMale: 32894,
    populationTotal: 65288,
    averageAge: 38.2,
    population0to5: 5214,
    population6to11: 5985,
  },
  {
    name: "Tyrone",
    province: "Ulster",
    displayOrder: 9,
    clubsGAA: 54,
    clubsLGFA: 40,
    clubsCamogie: 14,
    youthMalePlayers: 6067,
    youthFemalePlayers: 4559,
    fullMalePlayers: 2787,
    fullFemalePlayers: 1313,
    nonPlayers: 10298,
    totalPitches: 155,
    totalFloodlitPitches: 39,
    totalFullSizePitches: 102,
    teamsPerPitch: 4.7,
    teamsCamogie: 37,
    teamsLadiesFootball: 156,
    teamsHurling: 27,
    teamsFootball: 268,
    totalTeams: 488,
    populationFemale: 94267,
    populationMale: 94138,
    populationTotal: 188405,
    averageAge: 38.4,
    population0to5: 15407,
    population6to11: 15884,
  },
  // MUNSTER (6 counties)
  {
    name: "Clare",
    province: "Munster",
    displayOrder: 1,
    clubsGAA: 53,
    clubsLGFA: 24,
    clubsCamogie: 27,
    youthMalePlayers: 5669,
    youthFemalePlayers: 4972,
    fullMalePlayers: 3501,
    fullFemalePlayers: 1269,
    nonPlayers: 6826,
    totalPitches: 135,
    totalFloodlitPitches: 20,
    totalFullSizePitches: 88,
    teamsPerPitch: 7.9,
    teamsCamogie: 168,
    teamsLadiesFootball: 113,
    teamsHurling: 230,
    teamsFootball: 192,
    totalTeams: 703,
    populationFemale: 65021,
    populationMale: 62917,
    populationTotal: 217938,
    averageAge: 39.5,
    population0to5: 8803,
    population6to11: 10490,
  },
  {
    name: "Cork",
    province: "Munster",
    displayOrder: 2,
    clubsGAA: 151,
    clubsLGFA: 93,
    clubsCamogie: 68,
    youthMalePlayers: 21687,
    youthFemalePlayers: 19271,
    fullMalePlayers: 8900,
    fullFemalePlayers: 4591,
    nonPlayers: 20180,
    totalPitches: 404,
    totalFloodlitPitches: 77,
    totalFullSizePitches: 309,
    teamsPerPitch: 8.7,
    teamsCamogie: 360,
    teamsLadiesFootball: 574,
    teamsHurling: 703,
    teamsFootball: 816,
    totalTeams: 2453,
    populationFemale: 295311,
    populationMale: 288845,
    populationTotal: 584156,
    averageAge: 38.5,
    population0to5: 40177,
    population6to11: 48297,
  },
  {
    name: "Kerry",
    province: "Munster",
    displayOrder: 3,
    clubsGAA: 70,
    clubsLGFA: 41,
    clubsCamogie: 34,
    youthMalePlayers: 7435,
    youthFemalePlayers: 5489,
    fullMalePlayers: 3160,
    fullFemalePlayers: 1563,
    nonPlayers: 9947,
    totalPitches: 164,
    totalFloodlitPitches: 52,
    totalFullSizePitches: 92,
    teamsPerPitch: 6.1,
    teamsCamogie: 38,
    teamsLadiesFootball: 187,
    teamsHurling: 62,
    teamsFootball: 274,
    totalTeams: 561,
    populationFemale: 79071,
    populationMale: 77387,
    populationTotal: 156458,
    averageAge: 40.98,
    population0to5: 10173,
    population6to11: 11934,
  },
  {
    name: "Limerick",
    province: "Munster",
    displayOrder: 4,
    clubsGAA: 65,
    clubsLGFA: 34,
    clubsCamogie: 30,
    youthMalePlayers: 6726,
    youthFemalePlayers: 6020,
    fullMalePlayers: 3352,
    fullFemalePlayers: 1627,
    nonPlayers: 8103,
    totalPitches: 176,
    totalFloodlitPitches: 18,
    totalFullSizePitches: 98,
    teamsPerPitch: 8.4,
    teamsCamogie: 185,
    teamsLadiesFootball: 159,
    teamsHurling: 241,
    teamsFootball: 239,
    totalTeams: 824,
    populationFemale: 105084,
    populationMale: 104425,
    populationTotal: 209536,
    averageAge: 38.8,
    population0to5: 14076,
    population6to11: 16666,
  },
  {
    name: "Tipperary",
    province: "Munster",
    displayOrder: 5,
    clubsGAA: 71,
    clubsLGFA: 40,
    clubsCamogie: 38,
    youthMalePlayers: 7349,
    youthFemalePlayers: 6352,
    fullMalePlayers: 4131,
    fullFemalePlayers: 1798,
    nonPlayers: 7809,
    totalPitches: 209,
    totalFloodlitPitches: 35,
    totalFullSizePitches: 116,
    teamsPerPitch: 10.7,
    teamsCamogie: 189,
    teamsLadiesFootball: 214,
    teamsHurling: 451,
    teamsFootball: 386,
    totalTeams: 1240,
    populationFemale: 84256,
    populationMale: 83639,
    populationTotal: 167895,
    averageAge: 39.8,
    population0to5: 11766,
    population6to11: 13925,
  },
  {
    name: "Waterford",
    province: "Munster",
    displayOrder: 6,
    clubsGAA: 52,
    clubsLGFA: 24,
    clubsCamogie: 22,
    youthMalePlayers: 4456,
    youthFemalePlayers: 3820,
    fullMalePlayers: 2563,
    fullFemalePlayers: 967,
    nonPlayers: 3978,
    totalPitches: 118,
    totalFloodlitPitches: 16,
    totalFullSizePitches: 71,
    teamsPerPitch: 10.5,
    teamsCamogie: 132,
    teamsLadiesFootball: 140,
    teamsHurling: 257,
    teamsFootball: 219,
    totalTeams: 748,
    populationFemale: 64268,
    populationMale: 63095,
    populationTotal: 127363,
    averageAge: 39.5,
    population0to5: 8316,
    population6to11: 10431,
  },
  // LEINSTER (12 counties)
  {
    name: "Carlow",
    province: "Leinster",
    displayOrder: 1,
    clubsGAA: 27,
    clubsLGFA: 16,
    clubsCamogie: 10,
    youthMalePlayers: 2624,
    youthFemalePlayers: 2243,
    fullMalePlayers: 1343,
    fullFemalePlayers: 604,
    nonPlayers: 2238,
    totalPitches: 61,
    totalFloodlitPitches: 21,
    totalFullSizePitches: 41,
    teamsPerPitch: 6.2,
    teamsCamogie: 52,
    teamsLadiesFootball: 64,
    teamsHurling: 46,
    teamsFootball: 94,
    totalTeams: 256,
    populationFemale: 31146,
    populationMale: 30822,
    populationTotal: 61968,
    averageAge: 38.2,
    population0to5: 4285,
    population6to11: 5225,
  },
  {
    name: "Dublin",
    province: "Leinster",
    displayOrder: 2,
    clubsGAA: 84,
    clubsLGFA: 75,
    clubsCamogie: 62,
    youthMalePlayers: 26563,
    youthFemalePlayers: 23477,
    fullMalePlayers: 8414,
    fullFemalePlayers: 5306,
    nonPlayers: 28778,
    totalPitches: 412,
    totalFloodlitPitches: 31,
    totalFullSizePitches: 218,
    teamsPerPitch: 9,
    teamsCamogie: 317,
    teamsLadiesFootball: 503,
    teamsHurling: 514,
    teamsFootball: 629,
    totalTeams: 1963,
    populationFemale: 744548,
    populationMale: 713606,
    populationTotal: 1458154,
    averageAge: 37.4,
    population0to5: 98429,
    population6to11: 112871,
  },
  {
    name: "Kildare",
    province: "Leinster",
    displayOrder: 3,
    clubsGAA: 49,
    clubsLGFA: 40,
    clubsCamogie: 25,
    youthMalePlayers: 9334,
    youthFemalePlayers: 8169,
    fullMalePlayers: 3398,
    fullFemalePlayers: 1815,
    nonPlayers: 11315,
    totalPitches: 178,
    totalFloodlitPitches: 52,
    totalFullSizePitches: 108,
    teamsPerPitch: 8.3,
    teamsCamogie: 159,
    teamsLadiesFootball: 216,
    teamsHurling: 148,
    teamsFootball: 375,
    totalTeams: 898,
    populationFemale: 124510,
    populationMale: 123264,
    populationTotal: 247774,
    averageAge: 36.4,
    population0to5: 18777,
    population6to11: 22648,
  },
  {
    name: "Kilkenny",
    province: "Leinster",
    displayOrder: 4,
    clubsGAA: 41,
    clubsLGFA: 17,
    clubsCamogie: 34,
    youthMalePlayers: 4754,
    youthFemalePlayers: 4401,
    fullMalePlayers: 2191,
    fullFemalePlayers: 1076,
    nonPlayers: 6575,
    totalPitches: 118,
    totalFloodlitPitches: 15,
    totalFullSizePitches: 72,
    teamsPerPitch: 13.1,
    teamsCamogie: 256,
    teamsLadiesFootball: 75,
    teamsHurling: 387,
    teamsFootball: 225,
    totalTeams: 943,
    populationFemale: 52277,
    populationMale: 51883,
    populationTotal: 104160,
    averageAge: 39.21,
    population0to5: 7197,
    population6to11: 9138,
  },
  {
    name: "Laois",
    province: "Leinster",
    displayOrder: 5,
    clubsGAA: 48,
    clubsLGFA: 19,
    clubsCamogie: 10,
    youthMalePlayers: 3975,
    youthFemalePlayers: 3429,
    fullMalePlayers: 2432,
    fullFemalePlayers: 828,
    nonPlayers: 3844,
    totalPitches: 132,
    totalFloodlitPitches: 28,
    totalFullSizePitches: 78,
    teamsPerPitch: 6.9,
    teamsCamogie: 44,
    teamsLadiesFootball: 138,
    teamsHurling: 128,
    teamsFootball: 235,
    totalTeams: 545,
    populationFemale: 45599,
    populationMale: 46278,
    populationTotal: 91877,
    averageAge: 36.8,
    population0to5: 6964,
    population6to11: 8733,
  },
  {
    name: "Longford",
    province: "Leinster",
    displayOrder: 6,
    clubsGAA: 34,
    clubsLGFA: 17,
    clubsCamogie: 0,
    youthMalePlayers: 1949,
    youthFemalePlayers: 1509,
    fullMalePlayers: 1228,
    fullFemalePlayers: 510,
    nonPlayers: 2011,
    totalPitches: 60,
    totalFloodlitPitches: 16,
    totalFullSizePitches: 34,
    teamsPerPitch: 6.8,
    teamsCamogie: 0,
    teamsLadiesFootball: 81,
    teamsHurling: 19,
    teamsFootball: 134,
    totalTeams: 234,
    populationFemale: 23302,
    populationMale: 23449,
    populationTotal: 46751,
    averageAge: 38.3,
    population0to5: 3341,
    population6to11: 4169,
  },
  {
    name: "Louth",
    province: "Leinster",
    displayOrder: 7,
    clubsGAA: 40,
    clubsLGFA: 34,
    clubsCamogie: 7,
    youthMalePlayers: 4718,
    youthFemalePlayers: 3717,
    fullMalePlayers: 2057,
    fullFemalePlayers: 1170,
    nonPlayers: 4302,
    totalPitches: 98,
    totalFloodlitPitches: 32,
    totalFullSizePitches: 58,
    teamsPerPitch: 7.1,
    teamsCamogie: 12,
    teamsLadiesFootball: 113,
    teamsHurling: 21,
    teamsFootball: 265,
    totalTeams: 411,
    populationFemale: 70796,
    populationMale: 68907,
    populationTotal: 139703,
    averageAge: 37.6,
    population0to5: 10053,
    population6to11: 12366,
  },
  {
    name: "Meath",
    province: "Leinster",
    displayOrder: 8,
    clubsGAA: 60,
    clubsLGFA: 49,
    clubsCamogie: 20,
    youthMalePlayers: 8917,
    youthFemalePlayers: 7991,
    fullMalePlayers: 3821,
    fullFemalePlayers: 2171,
    nonPlayers: 9438,
    totalPitches: 161,
    totalFloodlitPitches: 42,
    totalFullSizePitches: 102,
    teamsPerPitch: 8.4,
    teamsCamogie: 78,
    teamsLadiesFootball: 302,
    teamsHurling: 312,
    teamsFootball: 348,
    totalTeams: 860,
    populationFemale: 110838,
    populationMale: 109988,
    populationTotal: 220826,
    averageAge: 36.3,
    population0to5: 17338,
    population6to11: 21539,
  },
  {
    name: "Offaly",
    province: "Leinster",
    displayOrder: 9,
    clubsGAA: 41,
    clubsLGFA: 13,
    clubsCamogie: 16,
    youthMalePlayers: 3439,
    youthFemalePlayers: 3117,
    fullMalePlayers: 2476,
    fullFemalePlayers: 694,
    nonPlayers: 3974,
    totalPitches: 95,
    totalFloodlitPitches: 24,
    totalFullSizePitches: 64,
    teamsPerPitch: 5.8,
    teamsCamogie: 88,
    teamsLadiesFootball: 56,
    teamsHurling: 116,
    teamsFootball: 115,
    totalTeams: 375,
    populationFemale: 41522,
    populationMale: 41628,
    populationTotal: 83150,
    averageAge: 38.4,
    population0to5: 5932,
    population6to11: 7303,
  },
  {
    name: "Westmeath",
    province: "Leinster",
    displayOrder: 10,
    clubsGAA: 46,
    clubsLGFA: 29,
    clubsCamogie: 15,
    youthMalePlayers: 4390,
    youthFemalePlayers: 3847,
    fullMalePlayers: 2041,
    fullFemalePlayers: 1135,
    nonPlayers: 4656,
    totalPitches: 123,
    totalFloodlitPitches: 31,
    totalFullSizePitches: 76,
    teamsPerPitch: 5.1,
    teamsCamogie: 50,
    teamsLadiesFootball: 126,
    teamsHurling: 69,
    teamsFootball: 147,
    totalTeams: 392,
    populationFemale: 48500,
    populationMale: 47721,
    populationTotal: 96221,
    averageAge: 38.1,
    population0to5: 7027,
    population6to11: 8438,
  },
  {
    name: "Wexford",
    province: "Leinster",
    displayOrder: 11,
    clubsGAA: 48,
    clubsLGFA: 38,
    clubsCamogie: 41,
    youthMalePlayers: 6027,
    youthFemalePlayers: 5497,
    fullMalePlayers: 2958,
    fullFemalePlayers: 1592,
    nonPlayers: 4812,
    totalPitches: 162,
    totalFloodlitPitches: 28,
    totalFullSizePitches: 104,
    teamsPerPitch: 8.02,
    teamsCamogie: 171,
    teamsLadiesFootball: 203,
    teamsHurling: 232,
    teamsFootball: 230,
    totalTeams: 836,
    populationFemale: 83142,
    populationMale: 80777,
    populationTotal: 163919,
    averageAge: 39.45,
    population0to5: 11178,
    population6to11: 13827,
  },
  {
    name: "Wicklow",
    province: "Leinster",
    displayOrder: 12,
    clubsGAA: 37,
    clubsLGFA: 29,
    clubsCamogie: 15,
    youthMalePlayers: 4317,
    youthFemalePlayers: 4204,
    fullMalePlayers: 2081,
    fullFemalePlayers: 1248,
    nonPlayers: 3030,
    totalPitches: 96,
    totalFloodlitPitches: 32,
    totalFullSizePitches: 57,
    teamsPerPitch: 8.4,
    teamsCamogie: 143,
    teamsLadiesFootball: 95,
    teamsHurling: 66,
    teamsFootball: 175,
    totalTeams: 479,
    populationFemale: 79287,
    populationMale: 76564,
    populationTotal: 155851,
    averageAge: 38.6,
    population0to5: 11023,
    population6to11: 13775,
  },
  // CONNACHT (5 counties)
  {
    name: "Galway",
    province: "Connacht",
    displayOrder: 1,
    clubsGAA: 80,
    clubsLGFA: 41,
    clubsCamogie: 37,
    youthMalePlayers: 11922,
    youthFemalePlayers: 10398,
    fullMalePlayers: 5165,
    fullFemalePlayers: 2380,
    nonPlayers: 13071,
    totalPitches: 226,
    totalFloodlitPitches: 42,
    totalFullSizePitches: 139,
    teamsPerPitch: 8.7,
    teamsCamogie: 263,
    teamsLadiesFootball: 206,
    teamsHurling: 327,
    teamsFootball: 426,
    totalTeams: 1222,
    populationFemale: 140803,
    populationMale: 136934,
    populationTotal: 277737,
    averageAge: 38.4,
    population0to5: 19227,
    population6to11: 22608,
  },
  {
    name: "Leitrim",
    province: "Connacht",
    displayOrder: 2,
    clubsGAA: 23,
    clubsLGFA: 17,
    clubsCamogie: 2,
    youthMalePlayers: 1989,
    youthFemalePlayers: 1735,
    fullMalePlayers: 1039,
    fullFemalePlayers: 625,
    nonPlayers: 1995,
    totalPitches: 48,
    totalFloodlitPitches: 11,
    totalFullSizePitches: 27,
    teamsPerPitch: 7,
    teamsCamogie: 4,
    teamsLadiesFootball: 68,
    teamsHurling: 8,
    teamsFootball: 110,
    totalTeams: 190,
    populationFemale: 17646,
    populationMale: 17553,
    populationTotal: 35199,
    averageAge: 40.2,
    population0to5: 2592,
    population6to11: 3045,
  },
  {
    name: "Mayo",
    province: "Connacht",
    displayOrder: 3,
    clubsGAA: 53,
    clubsLGFA: 35,
    clubsCamogie: 5,
    youthMalePlayers: 6823,
    youthFemalePlayers: 5395,
    fullMalePlayers: 2679,
    fullFemalePlayers: 1175,
    nonPlayers: 6135,
    totalPitches: 130,
    totalFloodlitPitches: 30,
    totalFullSizePitches: 82,
    teamsPerPitch: 8.6,
    teamsCamogie: 12,
    teamsLadiesFootball: 225,
    teamsHurling: 51,
    teamsFootball: 421,
    totalTeams: 709,
    populationFemale: 69578,
    populationMale: 68392,
    populationTotal: 137970,
    averageAge: 41.1,
    population0to5: 9474,
    population6to11: 11122,
  },
  {
    name: "Roscommon",
    province: "Connacht",
    displayOrder: 4,
    clubsGAA: 32,
    clubsLGFA: 25,
    clubsCamogie: 8,
    youthMalePlayers: 3299,
    youthFemalePlayers: 2928,
    fullMalePlayers: 1574,
    fullFemalePlayers: 784,
    nonPlayers: 3337,
    totalPitches: 86,
    totalFloodlitPitches: 18,
    totalFullSizePitches: 52,
    teamsPerPitch: 7.4,
    teamsCamogie: 47,
    teamsLadiesFootball: 119,
    teamsHurling: 34,
    teamsFootball: 187,
    totalTeams: 387,
    populationFemale: 35089,
    populationMale: 35170,
    populationTotal: 70529,
    averageAge: 40.2,
    population0to5: 5010,
    population6to11: 6011,
  },
  {
    name: "Sligo",
    province: "Connacht",
    displayOrder: 5,
    clubsGAA: 25,
    clubsLGFA: 20,
    clubsCamogie: 3,
    youthMalePlayers: 3059,
    youthFemalePlayers: 2374,
    fullMalePlayers: 1178,
    fullFemalePlayers: 652,
    nonPlayers: 1950,
    totalPitches: 74,
    totalFloodlitPitches: 12,
    totalFullSizePitches: 38,
    teamsPerPitch: 7.3,
    teamsCamogie: 2,
    teamsLadiesFootball: 102,
    teamsHurling: 33,
    teamsFootball: 144,
    totalTeams: 281,
    populationFemale: 35669,
    populationMale: 34529,
    populationTotal: 70198,
    averageAge: 40.2,
    population0to5: 4737,
    population6to11: 5634,
  },
];

// Report summary data (from pages 7, 8, 10, 11)
const reportSummary = {
  reportTitle: "No One Shouted Stop—Until Now",
  reportSubtitle: "The GAA's Response to Ireland's Demographic Shift",
  publishedDate: new Date("2025-12-01"),
  totalPopulation: 7052602,
  totalClubs: 2371,
  totalMembers: 760183,
  dublinCommuterBeltPopulation: 2304899,
  dublinCommuterBeltPopPercent: 32.7,
  dublinCommuterBeltClubsPercent: 18,
  dublinCommuterBeltMembersPercent: 25.7,
  easternSeaboardPopulation: 3071222,
  easternSeaboardPopPercent: 43.5,
  easternSeaboardClubsPercent: 18.6,
  easternSeaboardMembersPercent: 25.4,
  top50ClubsYouthPercent: 25.5,
  lowest1000ClubsYouthPercent: 22,
  birthsIn2010: 100291,
  birthsIn2024: 73478,
  birthRateDeclinePercent: 26.74,
};

async function seedDemographicsData() {
  console.log("🌱 Starting demographics data seed...");

  try {
    // Clear existing data
    console.log("🗑️  Clearing existing demographics data...");
    await prisma.demographicsCounty.deleteMany({});
    await prisma.demographicsProvince.deleteMany({});
    await prisma.demographicsReportSummary.deleteMany({});

    // Create provinces
    console.log("📍 Creating provinces...");
    const createdProvinces: Record<string, string> = {};
    for (const province of provincesData) {
      const created = await prisma.demographicsProvince.create({
        data: province,
      });
      createdProvinces[province.name] = created.id;
      console.log(`  ✓ Created province: ${province.name}`);
    }

    // Create counties
    console.log("🏘️  Creating counties...");
    for (const county of countiesData) {
      const provinceId = createdProvinces[county.province];
      if (!provinceId) {
        console.error(`  ✗ Province not found for county: ${county.name}`);
        continue;
      }

      await prisma.demographicsCounty.create({
        data: {
          name: county.name,
          provinceId,
          displayOrder: county.displayOrder,
          clubsGAA: county.clubsGAA,
          clubsLGFA: county.clubsLGFA,
          clubsCamogie: county.clubsCamogie,
          youthMalePlayers: county.youthMalePlayers,
          youthFemalePlayers: county.youthFemalePlayers,
          fullMalePlayers: county.fullMalePlayers,
          fullFemalePlayers: county.fullFemalePlayers,
          nonPlayers: county.nonPlayers,
          totalPitches: county.totalPitches,
          totalFloodlitPitches: county.totalFloodlitPitches,
          totalFullSizePitches: county.totalFullSizePitches,
          teamsPerPitch: county.teamsPerPitch,
          teamsCamogie: county.teamsCamogie,
          teamsLadiesFootball: county.teamsLadiesFootball,
          teamsHurling: county.teamsHurling,
          teamsFootball: county.teamsFootball,
          totalTeams: county.totalTeams,
          populationFemale: county.populationFemale,
          populationMale: county.populationMale,
          populationTotal: county.populationTotal,
          averageAge: county.averageAge,
          population0to5: county.population0to5,
          population6to11: county.population6to11,
          reportYear: 2025,
          censusYear: "2021/2022",
        },
      });
      console.log(`  ✓ Created county: ${county.name} (${county.province})`);
    }

    // Update province totals
    console.log("📊 Calculating province totals...");
    for (const provinceName of Object.keys(createdProvinces)) {
      const counties = await prisma.demographicsCounty.findMany({
        where: { provinceId: createdProvinces[provinceName] },
      });

      const totals = counties.reduce(
        (acc, county) => ({
          totalPopulation: acc.totalPopulation + (county.populationTotal || 0),
          totalClubsGAA: acc.totalClubsGAA + (county.clubsGAA || 0),
          totalClubsLGFA: acc.totalClubsLGFA + (county.clubsLGFA || 0),
          totalClubsCamogie: acc.totalClubsCamogie + (county.clubsCamogie || 0),
          totalPitches: acc.totalPitches + (county.totalPitches || 0),
          totalYouthMalePlayers:
            acc.totalYouthMalePlayers + (county.youthMalePlayers || 0),
          totalYouthFemalePlayers:
            acc.totalYouthFemalePlayers + (county.youthFemalePlayers || 0),
          totalFullMalePlayers:
            acc.totalFullMalePlayers + (county.fullMalePlayers || 0),
          totalFullFemalePlayers:
            acc.totalFullFemalePlayers + (county.fullFemalePlayers || 0),
          totalNonPlayers: acc.totalNonPlayers + (county.nonPlayers || 0),
          totalMembers:
            acc.totalMembers +
            (county.youthMalePlayers || 0) +
            (county.youthFemalePlayers || 0) +
            (county.fullMalePlayers || 0) +
            (county.fullFemalePlayers || 0) +
            (county.nonPlayers || 0),
        }),
        {
          totalPopulation: 0,
          totalClubsGAA: 0,
          totalClubsLGFA: 0,
          totalClubsCamogie: 0,
          totalPitches: 0,
          totalYouthMalePlayers: 0,
          totalYouthFemalePlayers: 0,
          totalFullMalePlayers: 0,
          totalFullFemalePlayers: 0,
          totalNonPlayers: 0,
          totalMembers: 0,
        }
      );

      await prisma.demographicsProvince.update({
        where: { id: createdProvinces[provinceName] },
        data: {
          totalPopulation: totals.totalPopulation,
          totalClubsGAA: totals.totalClubsGAA,
          totalClubsLGFA: totals.totalClubsLGFA,
          totalClubsCamogie: totals.totalClubsCamogie,
          totalPitches: totals.totalPitches,
          totalYouthMalePlayers: totals.totalYouthMalePlayers,
          totalYouthFemalePlayers: totals.totalYouthFemalePlayers,
          totalFullMalePlayers: totals.totalFullMalePlayers,
          totalFullFemalePlayers: totals.totalFullFemalePlayers,
          totalNonPlayers: totals.totalNonPlayers,
          totalMembers: totals.totalMembers,
        },
      });
      console.log(`  ✓ Updated totals for ${provinceName}`);
    }

    // Create report summary
    console.log("📋 Creating report summary...");
    await prisma.demographicsReportSummary.create({
      data: reportSummary,
    });
    console.log("  ✓ Created report summary");

    console.log("\n✅ Demographics data seed completed successfully!");
    console.log(`   - 4 provinces created`);
    console.log(`   - ${countiesData.length} counties created`);
    console.log(`   - 1 report summary created`);
  } catch (error) {
    console.error("❌ Error seeding demographics data:", error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

seedDemographicsData();
